language: python

notifications:
  email: false

env:
  matrix:
    # Ubuntu 14.04 versions
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.5"
  global:
    - DISTRIB="conda"
      NUMPY_VERSION="1.14" SCIPY_VERSION="0.19"
      SCIKIT_LEARN_VERSION="0.19" MATPLOTLIB_VERSION="2.2"
      SCIKIT_IMAGE_VERSION="0.13" SYMPY_VERSION="1.3"
      STATSMODELS_VERSION="0.8" SEABORN_VERSION="0.7"
      PANDAS_VERSION="0.20"

install:
    - source build_tools/install.sh

before_script:
    - make clean

script:
    - python build_tools/show-python-packages-versions.py
    - make test
