language: python

notifications:
  email: false

env:
  matrix:
    # Ubuntu 14.04 versions
    - DISTRIB="conda" PYTHON_VERSION="2.7"
      NUMPY_VERSION="1.9" SCIPY_VERSION="0.14.0"
      SCIKIT_LEARN_VERSION="0.16.1" MATPLOTLIB_VERSION="1.4.0"
      SCIKIT_IMAGE_VERSION="0.10.1" SYMPY_VERSION="0.7.5"
      STATSMODELS_VERSION="0.5" SEABORN_VERSION="0.6"
      PANDAS_VERSION="0.15"
    - DISTRIB="conda" PYTHON_VERSION="3.4"
      NUMPY_VERSION="1.9" SCIPY_VERSION="0.14.0"
      SCIKIT_LEARN_VERSION="0.16.1" MATPLOTLIB_VERSION="1.4.0"
      SCIKIT_IMAGE_VERSION="0.10.1" SYMPY_VERSION="0.7.5"
      STATSMODELS_VERSION="0.5" SEABORN_VERSION="0.6"
      PANDAS_VERSION="0.15"

before_install:
    - sudo apt-get install texlive texlive-latex-extra

install:
    - source continuous_integration/install.sh

before_script:
    - make clean

script:
    - python continuous_integration/show-python-packages-versions.py
    - make test
